package:
  name: riak
  version: "2.7.0"

source:
  fn: riak-2.7.0.tar.gz
  url: https://pypi.python.org/packages/85/f5/1a571ddc68f1dc7148f083f25210b7c7de8a9bc69d0ea5683ca6f3c189a9/riak-2.7.0.tar.gz
  md5: 84ab9c2c4cdefef0c01ca90c5071b881
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - riak = riak:main
    #
    # Would create an entry point called riak that calls riak.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.8.0
    - basho_erlastic >=2.1.1
    - python3_protobuf >=2.4.1,<2.6.0

  run:
    - python
    - six >=1.8.0
    - basho_erlastic >=2.1.1
    - python3_protobuf >=2.4.1,<2.6.0

test:
  # Python imports
  imports:
    - riak
    - riak.client
    - riak.codecs
    - riak.datatypes
    - riak.pb
    - riak.tests
    - riak.transports
    - riak.transports.http
    - riak.transports.tcp

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/basho/riak-python-client
  license: Apache Software License
  summary: 'Python client for Riak'
  license_family: Apache

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
